### ISSUE TITLE
best way to detect scroll into/out of viewport

### ISSUE THREAD

**Issue by mattparker** [juandopazo/yui3-scrollspy#1]
Hi,

A question, really.  I did something similar recently, by amending the gallery-beacon synthetic event (which had beacon:reached) to add beacon:left.  It's here (not got to doing a pull request on the gallery module yet) https://gist.github.com/mattparker/5636276.  This is just to fire the events, some other code listens and adds/removes styles when they fire.

The gallery-beacon sets a timeout, and checks for the Node.inDoc() every x ms.

This one throttles the scroll event.

As the Morgan Cheng commented in the original, page width/height change doesn't fire scroll so it might be missed.

I've no idea which might be better, performance wise.

With the beacon events, I can see that if you're using a lot, you'll end up with a lot of timeouts, which may be problematic.  But then you may end up with the same sort of thing with throttled scroll events.  Perhaps there's a case for some sort of normalised, throttled scroll event wrapper that might fire on viewport width/height/(orientation?) change too (perhaps configurably).  So you'd only ever end up with one lot of throttling/timeouts, with lots of listeners...

(Incidentally, mine also does some slightly unpleasant _detach / _attach stuff if the node is on longer in the document.  My use case has one delegated event listener on a page header, and the whole node can get swapped in and out during the app).

**Comment by juandopazo** [comment]
In the topic of throttling vs intervals I think throttling is better at least just because the user isn't scrolling/resizing all the time. You can also throttle the resize event using Y.throttle().

Another approach is to try to listen to the moment in which the user stops resizing/scrolling. The [`windowresize` event](http://yuilibrary.com/yui/docs/api/classes/YUI.html#event_windowresize) does that. And you can easily set it up for `scroll` with a [`debounce` function](https://github.com/juandopazo/yui3-debounce).

As for the reasons I wrote ScrollSpy this way, it's just one: I wanted to write the less amount of code possible, so I reused Y.Plugin.ScrollInfo. And in this case I don't need to check the resize event because resizing the window only hides nodes from the bottom and I'm interested in the nodes that appear/disappear from the top of the viewport.

Let me know if you end up using ScrollSpy and if you need any new features in it.
